name: Myplayersql
version: 1.0
main: me.kqn.myplayersql.Myplayersql
api-version: 1.16
commands:
  Myplayersql:
    description: Myplayersql插件
    aliases: mps
permissions:
  Myplayersql.op:
    description: Myplayersql所有权限
    default: op